Group2_Sis3/Controllers/KategoriController.cs
using Group2_Sis3.Data;
using Group2_Sis3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Group2_Sis3.Controllers
{
    public class KategoriController : Controller
    {
        private Konteksti _konteksti;
        public KategoriController(Konteksti kon)
        {
            _konteksti = kon;
        }
        public IActionResult Listo()
        {
           
            List<Kategoria> lista = _konteksti.Kategorite.ToList();
            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edito(Kategoria x)
        {
            if (ModelState.IsValid)
            {
                _konteksti.Kategorite.Update(x);
                _konteksti.SaveChanges();
                return RedirectToAction("Listo");
            }

            return View(x);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Fshi(Kategoria kat)
        {

                _konteksti.Kategorite.Remove(kat);
                _konteksti.SaveChanges();
                return RedirectToAction("Listo");
        }
        public IActionResult Fshi(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Kategoria kat = _konteksti.Kategorite.Find(id);
            if (kat == null)
            {
                return NotFound();
            }
            return View(kat);
        }
        public IActionResult Edito(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }

            Kategoria kat = _konteksti.Kategorite.Find(id);
            if (kat == null)
            {
                return NotFound();
            }
            return View(kat);
        }
        public IActionResult Krijo()
        {
            // Studenti stu = new();
            Kategoria kat = new Kategoria();
            // var stud3 = new Studenti();
            return View(kat);
        }
        [HttpPost]
        public IActionResult Krijo(Kategoria kat)
        {
            if (ModelState.IsValid)
            {
                _konteksti.Kategorite.Add(kat);
                _konteksti.SaveChanges();
                return RedirectToAction("Listo");
            }

            return View(kat);
        }
    }
}

Group2_Sis3/Controllers/ProfesorController.cs
using Group2_Sis3.Data;
using Group2_Sis3.Models;
using Microsoft.AspNetCore.Mvc;

namespace Group2_Sis3.Controllers
{
    public class ProfesorController : Controller
    {
        private Konteksti _konteksti;
        public ProfesorController(Konteksti kon)
        {
            _konteksti = kon;
        }
        public IActionResult Listo()
        {
            List<Profesori> lista = _konteksti.Profesoret.ToList();
            return View(lista);
        }
    }
}

Group2_Sis3/Controllers/StudentController.cs
using Group2_Sis3.Data;
using Group2_Sis3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Group2_Sis3.Controllers
{
    public class StudentController : Controller
    {
        private Konteksti _konteksti;
        public StudentController(Konteksti kon)
        {
            _konteksti = kon;
        }
        public IActionResult Listo()
        {
           
            List<Studenti> lista = _konteksti.Studentet.ToList();
            return View(lista);
        }
        public IActionResult Edito(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Studenti studentDb = _konteksti.Studentet.Find(id);
            if (studentDb == null)
            {
                return NotFound();
            }
            ViewBag.Kom = _konteksti.Komunat.ToList().Select(kom => new SelectListItem()
            {
                Text = kom.Emri,
                Value = kom.Id.ToString()
            });
            return View(studentDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edito(Studenti stud)
        {
            if (stud.KomunaId == 0)
            {
                ModelState.AddModelError("KomunaId", "Specifiko komunen");
            }
            if (ModelState.IsValid)
            {
                _konteksti.Studentet.Update(stud);
                _konteksti.SaveChanges();
                return RedirectToAction("Listo");
            }

            ViewBag.Kom = _konteksti.Komunat.ToList().Select(kom => new SelectListItem()
            {
                Text = kom.Emri,
                Value = kom.Id.ToString()
            });
            return View(stud);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Fshi(Studenti stud)
        {

                _konteksti.Studentet.Remove(stud);
                _konteksti.SaveChanges();
                return RedirectToAction("Listo");
        }
        public IActionResult Fshi(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Studenti studentDb = _konteksti.Studentet.Find(id);
            if (studentDb == null)
            {
                return NotFound();
            }
            ViewBag.Kom = _konteksti.Komunat.ToList().Select(kom => new SelectListItem()
            {
                Text = kom.Emri,
                Value = kom.Id.ToString()
            });
            return View(studentDb);
        }
        
        public IActionResult Krijo()
        {
            // Studenti stu = new();
            Studenti stu2 = new Studenti();
            // var stud3 = new Studenti();
            ViewBag.Komunat = _konteksti.Komunat.ToList().Select(kom => new SelectListItem()
            {
                Text = kom.Emri,
                Value = kom.Id.ToString()
            });
            return View(stu2);
        }
        [HttpPost]
        public IActionResult Krijo(Studenti stud)
        {
            if (stud.KomunaId==0)
            {
                ModelState.AddModelError("KomunaId","Specifiko komunen");
            }
            if (ModelState.IsValid)
            {
                _konteksti.Add(stud);
                _konteksti.SaveChanges();
                return RedirectToAction("Listo");
            }

            ViewBag.Komunat = _konteksti.Komunat.ToList().Select(kom => new SelectListItem()
            {
                Text = kom.Emri,
                Value = kom.Id.ToString()
            });
            return View(stud);

        }
    }
}

Group2_Sis3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group2_Sis3</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Group2_Sis3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Group2_Sis3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Listo">Studentet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profesor" asp-action="Listo">Profesoret</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kategori" asp-action="Listo">Kategoria</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - Group2_Sis3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>